### ISSUE TITLE
youtube recommended videos

### ISSUE THREAD

**Issue by stuartlamour** [Microsoft/moodle-filter_oembed#10]
Client reports they would like youtube to not display recommended videos.
Probably an option to set the param for displaying related videos.

**Comment by jamesmcq** [comment]
Hi @stuartlamour - apologies I have not been able to address this issue earlier. This plugin is now maintained by POET (https://github.com/poetgroup/moodle-filter_oembed), and the next version contains many changes. If you are still interested in pursuing this request, please get in touch with the new maintainers. Thank you!
