### ISSUE TITLE
soundcloud and ted lazyload does not autoplay

### ISSUE THREAD

**Issue by stuartlamour** [Microsoft/moodle-filter_oembed#9]
Not sure if soundcloud or ted have autoplay param, but if it does going from image to iframe with autoplay would be a better user experience than having to click twice to play.

**Comment by jamesmcq** [comment]
Hi @stuartlamour - apologies I have not been able to address this issue earlier. This plugin is now maintained by POET (https://github.com/poetgroup/moodle-filter_oembed), and the next version contains many changes. If you are still interested in pursuing this request, please get in touch with the new maintainers. Thank you!
